### ISSUE TITLE
Logo Contribution 

### ISSUE THREAD

**Issue by ghostofiht** [mlavik1/Retro3D#4]
Hello, I see you started a new open source project. I support open source projects with my logo designs. I would also like to make a contribution to the Retro 3D project. I have a great design for this project. You want to see this?

**Comment by mlavik1** [comment]
@ghostofiht Sure, that would be really nice!
I have no artistic skills myself, so I wouldn't be able to make a good logo :)

**Comment by ghostofiht** [comment]
@mlavik1 This it doesn't matter. Github is a big community. Those who want to make graphic contributions like me will always be. My design is as follows. I made different color combinations.You can choose what you want or suggest a different color. The main idea of ​​design is; "Game pixels" and "2.5D appearance". I chose the font type retro. Thus I provided the integrity of the design. If you want any change in design, don't hesitate to say it. 
![retro3d](https://user-images.githubusercontent.com/42060713/55721864-31515800-5a0d-11e9-8c7b-adba84022a22.jpg)


Also, i made the following version to use in limited areas like Favicon.

![retro_samll](https://user-images.githubusercontent.com/42060713/55722528-3c0cec80-5a0f-11e9-8ca8-ee38eb1d3a5e.jpg)

**Comment by mlavik1** [comment]
Thank you very much!
I like the first two, but I think the blue one (second image) fits best :) 

I really like it and think it fits the project very well. It's retro but doesn't look too old either, so it works well for a game engine for old-school 2.5D games.

As file icon I think I will use something like this:
![image](https://user-images.githubusercontent.com/6906872/55734126-4931d780-5a1f-11e9-9000-162ba1f36975.png)
(I just copied the right "3D" part of the logo you made, and copy and flipped the top line in MsPaint 😄  )

I will make a "contributions" file and add you as a contributor there.
Thanks a lot for the contribution! I dediced a few days ago to continue working on this project again, and now that I have a logo I'm extra motivated 👍

**Comment by ghostofiht** [comment]
Wonderful choice ! I sent you a high-resolution version of the logo and logotype with PR. https://github.com/mlavik1/Retro3D/pull/5 

I also noticed that your repo does not have a license. If you'd like to add a license, you can do this with the instructions here: https://help.github.com/en/articles/adding-a-license-to-a-repository. License is an important detail for open source projects. 

And please feel free to tell us if you have logo requests for your other projects. 

Good work!

**Comment by mlavik1** [comment]
@ghostofiht Thanks, I just merged it.

Oh, looks like I had forgotten that! haha
Thanks for letting me know.

By the way, how do you want to appear in the contributors list? With username (and link to GitHub)?

**Comment by ghostofiht** [comment]
User step slightly ridiculous. 😆  A link will be better. 
Thanks @mlavik1

**Comment by mlavik1** [comment]
Done: https://github.com/mlavik1/Retro3D/blob/master/CREDITS.md
